### ISSUE TITLE
Error when creating new category via web service

### ISSUE THREAD

**Issue by sanctusmob** [dim00z/gshoppingflux#81]
Prestashop 1.7.5

apache error log
`[Mon Aug 26 15:13:58.220276 2019] [proxy_fcgi:error] [pid 30481] [client 79.129.43.209:36268] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function getLanguages() on null in /var/www/vhosts/toys-shop.gr/httpdocs/modules/gshoppingflux/gshoppingflux.php:160\nStack trace:\n#0 /var/www/vhosts/toys-shop.gr/httpdocs/modules/gshoppingflux/gshoppingflux.php(250): GShoppingFlux->initDb(1)\n#1 /var/www/vhosts/toys-shop.gr/httpdocs/classes/Hook.php(966): GShoppingFlux->hookActionObjectCategoryAddAfter(Array)\n#2 /var/www/vhosts/toys-shop.gr/httpdocs/classes/Hook.php(351): HookCore::coreCallHook(Object(GShoppingFlux), 'hookactionObjec...', Array)\n#3 /var/www/vhosts/toys-shop.gr/httpdocs/classes/Hook.php(903): HookCore::callHookOn(Object(GShoppingFlux), 'actionObjectCat...', Array)\n#4 /var/www/vhosts/toys-shop.gr/httpdocs/classes/ObjectModel.php(601): HookCore::exec('actionObjectCat...', Array)\n#5 /var/www/vhosts/toys-shop.gr/httpdocs/classes/Category.php(191): ObjectModelCore->add(true, false)\n#6 /var/www/vhosts/toys-shop.gr/httpdocs/classes/webservice/WebserviceRequest.php(1566): CategoryCore-...\n'`

The line 160 is
$languages = $this->context->controller->getLanguages();
in function public function initDb($id_shop)

**Comment by sanctusmob** [comment]
I fix the error by replacing the line 160 in gshoppingflux.php
from 
$languages = $this->context->controller->getLanguages();
to
$languages = Language::getLanguages(true, $id_shop);

I don't know if every think else is working in function as it would be...
